name: security-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - dlib
  - cudatoolkit-dev
  - hnswlib
  - scikit-learn
  - nomkl
  - pip
